spring:
  application:
    name: crowdfunding-backend

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/crowdfunding}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
     show-sql: false
     hibernate:
     ddl-auto: true

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-stacktrace: never

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-change-this-in-production-min-256-bits}
  expiration: 86400000 # 24 hours in milliseconds

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Logging
logging:
  level:
    root: INFO
    com.crowdfunding: DEBUG
    org.jdbi: DEBUG
